name: Benchmark
on:
  pull_request:
    paths:
      - ".github/workflows/benchmark.yml"
      - "package.json"
      - "types/**"
      - "benchmarks/typescript/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/benchmark.yml"
      - "package.json"
      - "types/**"
      - "benchmarks/typescript/**"
permissions:
  contents: read

jobs:
  typescript:
    runs-on: ubuntu-20.04
    name: Benchmark TypeScript Types
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup node
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3.1.1
        with:
          node-version: 16

      - run: npm install

      - run: npx ts-benchmark -p ./benchmarks/typescript/simple -f 17/100000 18 29 32 -b master --colors
        env:
          DB_URL: ${{ secrets.DB_URL }}
